name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Python dependencies
        run: python3 -m pip install --break-system-packages setuptools

      - name: Install AppImage dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libfuse2 squashfs-tools patchelf

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npx --no-install electron-builder --${{ matrix.os == 'macos-latest' && 'mac' || 'linux' }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-app-${{ matrix.os }}
          path: |
            dist/*.AppImage
            dist/*.deb
            dist/*.dmg

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*

  aur-publish:
    name: Publish to AUR
    runs-on: ubuntu-latest
    needs: release
    container:
      image: archlinux:latest
    steps:
      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git openssh base-devel pacman-contrib
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur
          chmod 600 ~/.ssh/aur
          git config --global core.sshCommand "ssh -i ~/.ssh/aur -o StrictHostKeyChecking=no"
      - name: Configure Git
        run: |
          git config --global user.name "klpod221"
          git config --global user.email "klpod221@gmail.com"
      - name: Clone AUR Repository
        run: git clone ssh://aur@aur.archlinux.org/kerminal-bin.git /tmp/aur-repo
      - name: Change Repo Ownership
        run: chown -R builder:builder /tmp/aur-repo
      - name: Update PKGBUILD
        run: |
          sudo -u builder bash -c '
            cd /tmp/aur-repo
            VERSION=${{ github.ref_name }}
            CLEAN_VERSION=${VERSION#v}
            sed -i "s/^pkgver=.*/pkgver=$CLEAN_VERSION/" PKGBUILD
            updpkgsums
          '
      - name: Update .SRCINFO
        run: |
          sudo -u builder bash -c '
            cd /tmp/aur-repo
            makepkg --printsrcinfo > .SRCINFO
          '
      - name: Commit and Push to AUR
        run: |
          cd /tmp/aur-repo
          git config --global --add safe.directory /tmp/aur-repo
          if ! git diff-index --quiet HEAD; then
            git add PKGBUILD .SRCINFO
            git commit -m "Update to version ${{ github.ref_name }}"
            git push
          else
            echo "No changes to commit."
          fi
